# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_remove_status_favorited'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='favorited',
            field=models.ManyToManyField(to='feed.Status'),
        ),
    ]
