# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-29 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160328_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='agunz',
            field=models.CharField(default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='darkgunz',
            field=models.CharField(default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='drgunz',
            field=models.CharField(default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='egunz',
            field=models.CharField(default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='fgunz',
            field=models.CharField(default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='hggunz',
            field=models.CharField(default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phgunz',
            field=models.CharField(default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='reloaded',
            field=models.CharField(default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='rival',
            field=models.CharField(default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='sgunz',
            field=models.CharField(default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='skype',
            field=models.CharField(default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='twitch',
            field=models.CharField(default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='twitter',
            field=models.CharField(default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='youtube',
            field=models.CharField(default='None', max_length=24),
        ),
    ]
