# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_favorited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='favorited',
            field=models.ManyToManyField(related_name='favorite', to='feed.Status'),
        ),
    ]
