# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_useraccount_prof_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='favorited',
            field=models.ManyToManyField(default='1', related_name='favorites', to='feed.Status'),
        ),
    ]
