# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160323_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='favorited',
            new_name='favorites',
        ),
    ]
