# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20160323_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites', to='feed.Status'),
        ),
    ]
