# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20160323_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='favorites',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='favorites',
            field=models.SlugField(default=0, verbose_name='feed.Status'),
            preserve_default=False,
        ),
    ]
