# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-24 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20160324_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='favorited',
            field=models.ManyToManyField(related_name='favorited', to='feed.Status'),
        ),
    ]
