# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-24 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20160324_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='favorited',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='favorited',
            field=models.CharField(default='1', max_length=72),
        ),
    ]
