# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-24 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_remove_status_favorites'),
        ('users', '0016_auto_20160324_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='favorited',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='feed.Status'),
        ),
    ]
