# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-24 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20160324_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='favorites',
            new_name='favorited',
        ),
    ]
