# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20160323_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='favorited',
        ),
    ]
