# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_remove_status_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='favorites',
        ),
    ]
